services:

  mail-service:
    image: amsterdam/amsterdam-mail-service:latest
    build:
      context: .
      dockerfile: Containerfile
    command: ["yarn", "run", "start:dev"]
    env_file: .env
    ports:
      - "3001:3001"
    volumes:
      - ".:/app"
    networks:
      - amsterdam-mail-service
    depends_on:
      keycloak:
        condition: service_healthy
      mailpit:
        condition: service_healthy

  mailpit:
    image: axllent/mailpit:v1.27.8
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - amsterdam-mail-service
    environment:
      MP_SMTP_AUTH_ALLOW_INSECURE: "true"
      MP_SMTP_AUTH: "test_smtp_user:smtp_secret"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8025/readyz"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  keycloak:
    build:
      context: docker/keycloak
    image: amsterdam/amsterdam-mail-service-keycloak:latest
    command:
      - "/opt/keycloak/bin/kc.sh"
      - "start-dev"
      - "--http-port"
      - "8002"
      - "--health-enabled"
      - "true"
    ports:
      - "8002:8002"
    volumes:
      - "./docker/keycloak/import:/import"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    networks:
      amsterdam-mail-service:
        aliases:
          - iam
    healthcheck:
      test:
        - "CMD"
        - "curl"
        - "--head"
        - "-fsS"
        - "http://localhost:9000/health/ready"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  emulator.vault.azure.net:
    image: ghcr.io/rokeller/azure-keyvault-emulator:v2.1.1
    ports:
      - "11001:11001"
    networks:
      - amsterdam-mail-service

  collector:
    image: otel/opentelemetry-collector-contrib:0.138.0
    ports:
      - "4317:4317"
    volumes:
      - ./docker/otel-collector/otel-collector-config-dev.yaml:/etc/otelcol-contrib/config.yaml
    networks:
      - amsterdam-mail-service

networks:
    amsterdam-mail-service:
